//! An async, `no_std` CANopen master library.
//!
//! Built around the roles a CANopen *client/master* needs when talking to
//! third-party nodes (battery BMSes, drives, sensors):
//!
//! - [`NodeClient`]: per-node frame dispatch — feed received frames in, get
//!   typed [`NodeEvent`]s (heartbeat, EMCY, PDO, SYNC) out
//! - [`SdoClient`]: expedited, segmented and block SDO transfers
//! - [`HeartbeatMonitor`]: liveness supervision, fed by the dispatcher
//! - [`EmcyMonitor`]: emergency tracking, fed by the dispatcher
//! - [`pdo`]: typed PDO reception via [`PdoPayload`] and [`PdoSlot`], plus
//!   remote PDO reconfiguration over SDO ([`NodeClient::configure_tpdo`])
//! - NMT master commands, SYNC production, RPDO transmission
//!   ([`NodeClient::send_nmt`] / [`send_sync`](NodeClient::send_sync) /
//!   [`send_rpdo`](NodeClient::send_rpdo))
//!
//! The library is transport-agnostic over the async [`embedded_can`] traits
//! and executor-agnostic (no embassy executor required; timeouts use
//! `embassy-time`).

#![cfg_attr(not(test), no_std)]
#![allow(async_fn_in_trait)]

pub mod dict;
mod emcy;
mod frame;
mod heartbeat;
mod node;
pub mod pdo;
mod protocol;
mod sdo;

pub use dict::{Domain, OctetString, SdoArray, SdoEntry, SdoScalar, VisibleString};

/// Include an object dictionary generated by `canopen-async-codegen`'s
/// `build_dictionary(name, eds_path)` in a build script. The name is the
/// label passed there:
///
/// ```ignore
/// #[allow(dead_code)]
/// mod dict {
///     canopen_async::include_dictionary!(ENYRING);
/// }
/// ```
#[macro_export]
macro_rules! include_dictionary {
    ($name:ident) => {
        include!(env!(concat!("CANOPEN_DICTIONARY_", stringify!($name))));
    };
}
pub use emcy::{EmcyMessage, EmcyMonitor};
pub use frame::{NmtCommand, NmtState};
pub use heartbeat::HeartbeatMonitor;
pub use node::{NodeClient, NodeEvent};
pub use pdo::{PdoConfig, PdoMappingEntry, PdoPayload, PdoSlot};
pub use protocol::{BlockAck, BlockInit, BlockUploadInit, BlockUploadSegment, Segment};
pub use sdo::{SdoClient, SdoError, SeekFrom, StreamReader, StreamSeeker, SdoOverrides};
